### ISSUE TITLE
Always sets tracking speed to 4

### ISSUE THREAD

**Issue by coding-cucumber** [lujjjh/LinearMouse#26]
No matter what I set the tracking speed to, it always reverts to step 4. I am on macOS Monterey.

![img](https://user-images.githubusercontent.com/59795195/145081014-c998096f-e87c-423e-be18-fd26705c639a.png)

**Comment by coding-cucumber** [comment]
@mreser99 I see. In the readme, it should say that the tracking speed is locked. (to step 4, seemingly)

**Comment by lujjjh** [comment]
To make it clear, tracking speed in System Preference actually refers to cursor acceleration rather than cursor sensitivity (or pointer speed in Windows). When linear movement is enabled, it will be locked. We're still looking for ways to adjust cursor sensitivity in macOS (#15). Anyway, I agree that I should mention it on “Enable linear movement” option. Thank you.

**Comment by coding-cucumber** [comment]
@lujjjh Thanks for the clarification. We can probably close this issue now.

**Comment by lujjjh** [comment]
Cursor acceleration & sensitivity is now implemented. Maybe you'll interested in https://github.com/lujjjh/LinearMouse/issues/15#issuecomment-989893525.

**Comment by tylerweitzman** [comment]
> To make it clear, tracking speed in System Preference actually refers to cursor acceleration rather than cursor sensitivity (or pointer speed in Windows). When linear movement is enabled, it will be locked. We're still looking for ways to adjust cursor sensitivity in macOS (#15). Anyway, I agree that I should mention it on “Enable linear movement” option. Thank you.

Since sys preferences tracking speed is relevant to acceleration, What is the default sensitivity that supposedly remains fixed? Is that 1600 in linearmouse? What does 1600 mean mathematically in terms of the relationships of pixels to mouse DPI?

Thanks

**Comment by lujjjh** [comment]
Hey, @tylerweitzman!

Currently, I use the same algorithm to calculate the sensitivity as [CursorSense](https://plentycom.jp/en/cursorsense/index.html#:~:text=Sensitivity%20represents%20the%20distance%20the%20cursor%20moves%20when%20the%20mouse%20is%20moved%201%20inch.%20The%20OS%20always%20uses%20a%20default%20value.), that is, 2000 - *the pointer resolution reported by pointer devices* (HIDPointerResolution). So, different devices may report different pointer resolutions.

The reasons why LinearMouse uses a constant value 1600 as the default sensitivity are

1. LinearMouse does not support per-device settings for now (which is planned to be added in v0.6 or v0.7). So I should choose a global default sensitivity.
2. It *seems* that most devices report their pointer resolution as 400.

When LinearMouse supports per-device settings, the default sensitivity will vary across devices rather than being a constant value.

So far, I can't tell the exact relationship between the pointer resolution and the actual DPI. The pointer resolution seems to be like the screen resolution. Higher resolution means higher accuracy but slower pointer speed. So the actual DPI should be inversely proportional to the pointer resolution. That's why in the current version, the pointer speed does not increase **linearly** with the sensitivity. I may optimize it in the future.
