### ISSUE TITLE
Can't install LinearMouse because Apple can't search it for malware

### ISSUE THREAD

**Issue by crashmit** [lujjjh/LinearMouse#31]
![image](https://user-images.githubusercontent.com/58466626/145594940-ab8104b7-4cfc-4f77-b78d-a62cd93a2ad9.png)
After dragging the program into my applications folder, I can't open it and get this error message instead, that can't be ignored :(

I'm on MacOS Monterrey

**Comment by lujjjh** [comment]
Just like opening other apps from unidentified developers (or people who don't pay $99 every year to Apple), you may right click the app and choose open rather than double click it directly.

A more official but complicated workaround can also be found [here](https://support.apple.com/en-us/HT202491).

**Comment by crashmit** [comment]
Thank you very much! I'm only using Macs for work so this wasn't obvious to me. Fascinating, that this works 😅 Maybe you can point that out on this Git's main page. I'm sure, there are other people out there who don't know that.

**Comment by lujjjh** [comment]
> I'm sure, there are other people out there who don't know that.

I believe you're right. I'll add this to the documentation. Thank you for pointing it out.
