### ISSUE TITLE
LinearMouse does not work on 10.15.7 or lower

### ISSUE THREAD

**Issue by debrunet** [lujjjh/LinearMouse#38]
Would it be possible to lower the minimum macOS requirements of the app? I am still running 10.15.7 but am unable to us it as it requires 11 or higher.
![png](https://user-images.githubusercontent.com/61621711/147403107-e9813093-1722-4b97-a070-4f3154566060.png)

**Comment by lujjjh** [comment]
Hi, @debrunet!

LinearMouse can be ported to macOS Catalina technically like the previous versions (< 0.3). However, I discovered that there are some differences between macOS Catalina and macOS Big Sur+ that take additional time to resolve and double the test workload. In addition, in order to make it compatible with macOS Catalina, new APIs would be not available.

Nonetheless, since macOS Catalina won't reach end-of-life until the end of next year, it's still reasonable to support it now. If this is a common request, I'll do it.

**Comment by lujjjh** [comment]
LinearMouse was ported to macOS 10.15 in 9a81221 with as few changes as possible. This is **totally untested** and I've no idea if the mouse sensitivity and acceleration work properly because I don't have Catalina installed. If you'd like to give it a shot, you can get the binary [here](https://github.com/lujjjh/LinearMouse/actions/runs/1624052497z).

**Comment by lujjjh** [comment]
I put it to the test on Catalina, and everything seems to work fine. You may try [v0.3.2](https://github.com/lujjjh/LinearMouse/releases/tag/v0.3.2).

**Comment by debrunet** [comment]
Can confirm that it's working completely on my 10.15.7 machine! This app just replaced DiscreteScroll, SensibleSideButtons and Scroll Reverser—all at once! Awesome 😁

I have found a small bug though. In System Preferences.app, the back and forward buttons only work when the cursor is hovering the titlebar of the window, not when the cursor is in the content of the window. This also happens on Monterey.

Nice work!
