### ISSUE TITLE
Version 0.3.2 cannot be opened on M1 Mac

### ISSUE THREAD

**Issue by t-liu93** [lujjjh/LinearMouse#40]
Just got a new M1 Mac Mini today, installed 0.3.2 but it's not working. Tried 0.3.1 and it can be used.
OS version: Monterey 12.0.1
<img width="734" alt="Screenshot 2021-12-29 at 21 35 56" src="https://user-images.githubusercontent.com/14870453/147701492-4d2b90de-3479-414f-af4f-3e21aa9263a9.png">

**Comment by lujjjh** [comment]
I believe this regression was introduced in #30. I was trying to get the code signing certificate fixed instead of an ad-hoc one, so that upgrading LinearMouse wouldn't require regranting permissions.

It seems that there are some restrictions on development certificates. (Please correct me if I'm wrong.) For the time being, I'll revert it to an ad-hoc code sign.

**Comment by lujjjh** [comment]
I think I've figured out what was going on. I reinstalled macOS and obtained a new development certificate, and the old one was revoked automatically.

Please verify that [v0.3.3](https://github.com/lujjjh/LinearMouse/releases/tag/v0.3.3) has resolved this issue. Thank you for reporting this!

**Comment by t-liu93** [comment]
Hi @lujjjh I just want to confirm that v0.3.3 has resolved this issue. Thanks for the quick update!
