### ISSUE TITLE
Received message: "LinearMouse.app" will damage your computer. You should move it to the Bin.

### ISSUE THREAD

**Issue by debrunet** [lujjjh/LinearMouse#43]
Just received this message after having LinearMouse installed for a day:
![png0](https://user-images.githubusercontent.com/61621711/147749813-f0cc6d46-1d1f-46e2-b079-aa313f5d9de6.png)
Pressing the question-mark in the top leads to:
![png1](https://user-images.githubusercontent.com/61621711/147749836-1f2a961c-7e1f-4cd5-ad07-f357afd4afdb.png)
I pressed Cancel, but did want to make a report for it. As I have never seen this message pop up before with any unsigned app.

**Comment by lujjjh** [comment]
Hi, @debrunet!

This is because after I reinstalled macOS, [my previous development certificate was unintentionally revoked](https://github.com/lujjjh/LinearMouse/issues/40).

LinearMouse v0.3.2 is the only version that is affected. So if you are using v0.3.2, please upgrade to [v0.3.3](https://github.com/lujjjh/LinearMouse/releases/tag/v0.3.3).
