### ISSUE TITLE
Question: does LinearMouse affect trackpad behaviour?

### ISSUE THREAD

**Issue by lsorber** [lujjjh/LinearMouse#46]
Or does it only apply to external mice?

**Comment by lujjjh** [comment]
It only applies to external mice.

**Comment by Atemu** [comment]
Is it possible to make it work with trackpads?

CursorSense seems to have done it somehow but I'm not sure they use the same mechanism as you do.

**Comment by lujjjh** [comment]
Hi, @Atemu!

> Is it possible to make it work with trackpads?

Technically, yes. LinearMouse, as the name suggests, is designed to ignore trackpads. It should affect trackpads if the following guard in the code is removed:

https://github.com/linearmouse/linearmouse/blob/aa29cd7ff6b37586fa04190f834f308c817d6293/LinearMouse/CursorManager.swift#L99-L102

I believe trackpads use `kIOHIDPointerAccelerationTypeKey` instead of `kIOHIDMouseAccelerationTypeKey`. So if you'd like to change the acceleration of trackpads, `kIOHIDPointerAccelerationTypeKey` could be the right property.

> CursorSense seems to have done it somehow but I'm not sure they use the same mechanism as you do.

I think so, though CursorSense isn't open-sourced. :)

**Comment by Atemu** [comment]
> CursorSense isn't open-sourced

That's why I'm here ;)

If it's feasible by your evaluation, I'll create a separate issue and maybe try to hack on it myself. Thanks!
